### PR TITLE
Add .gitignore

### PR DESCRIPTION
**Pull request by codewithPrasiddha**

### CODE REVIEW

**Comment by Prasiddha-Thapaliya** [comment]
Suggestion to add other sensitive file names

**Review by Prasiddha-Thapaliya — APPROVED** [review]
Valid entry

**Review by Prasiddha-Thapaliya — APPROVED** [review]

**Review by Prasiddha-Thapaliya — APPROVED** [review]
Works

**Comment by codewithPrasiddha** [comment]
Ok

**Review by Prasiddha-Thapaliya — APPROVED** [review]

**Review by Prasiddha-Thapaliya — COMMENTED** [review]
Works

**Review by Prasiddha-Thapaliya — APPROVED** [review]

**Review by codewithPrasiddha — COMMENTED** [review]
Working

**Pull request closed without merging**
